"""Every word it says, in German."""
from ..words.lookup import speaks

DE = {
    "start": "Start", "end": "Ende", "ret": "Rückgabe",
    "yes": "Wahr", "no": "Falsch", "again": "nochmal?",
    "key_oval": "Start / Ende", "key_rect": "Verarbeitung",
    "key_io": "Eingabe / Ausgabe", "key_diamond": "Entscheidung",
    "key_hex": "Schleife", "key_sub": "Modul aufrufen",
    "palette": "Palette", "shapes": "Formen",
    # ---- the Style side: the words, the highlighter, the borders
    "t_head": "Schrift", "t_face": "Schriftart",
    "t_sans": "Schlicht", "t_serif": "Buch",
    "t_mono": "Code", "t_hand": "Hand",
    "t_size": "Größe", "t_smaller": "Kleiner",
    "t_bigger": "Größer", "t_bold": "Fett",
    "t_italic": "Kursiv", "t_under": "Unterstrichen",
    "t_strike": "Durchgestrichen", "t_color": "Farbe",
    "t_mark": "Markierung", "t_mark_none": "Keine Markierung",
    "t_mark_own": "Andere Farbe", "m_yellow": "Gelb",
    "m_green": "Grün", "m_pink": "Rosa",
    "m_blue": "Blau", "m_orange": "Orange",
    "t_weight": "Linienstärke", "t_thin": "Dünn",
    "t_normal": "Normal", "t_thick": "Dick",
    "t_border": "Rahmen", "t_dashed": "Gestrichelter Rahmen",
    "t_copy_look": "Stil kopieren", "t_paste_look": "Stil einfügen",
    "t_size_list": "Größe wählen",
    "selected": "Ausgewählte Form", "rest": "Linien und Papier",
    "fill": "Füllung", "outline": "Umriss", "text": "Text",
    "paper": "Papier", "grid": "Raster", "show_grid": "Raster anzeigen",
    "lines": "Linien und Pfeile", "reset": "Den ganzen Stil zurücksetzen",
    "download": "Herunterladen", "dl_size": "Größe",
    "files": "Dateien", "import_head": "Importieren",
    "dl_svg": "SVG herunterladen", "dl_png": "PNG herunterladen",
    "print_it": "Diagramm drucken",
    "print_head": "Drucken",
    "print_go": "Drucken…",
    "print_paper": "Papier",
    "print_wide": "Quer",
    "print_fit": "Auf eine Seite bringen",
    "print_note": "Gedruckt wird schlicht: keine Farben, nur Linien und Wörter. Welcher Drucker und wie viele Kopien, fragt dein Browser selbst — eine Seite darf das nicht fragen.",
    "panel": "Bereich", "panel_tip": "Bereich ein- oder ausblenden",
    "png_tip": "Wie groß das PNG wird",
    "fit": "Einpassen", "actual": "Original", "zoom_in": "Vergrößern",
    "slide_left": "Links", "slide_right": "Rechts", "slide_up": "Hoch", "slide_down": "Runter",
    "hold_locked": "Fixiert", "hold_loose": "Frei",
    "lock_tip": "Das Diagramm bleibt an seinem Platz und wird in der Fläche gescrollt",
    "loose_tip": "Das Diagramm frei verschieben; eine Ecke bleibt immer sichtbar",
    "zoom_out": "Verkleinern", "pixels": "Pixel",
    "dl_scale": "Mal so groß wie gezeichnet",
    "dl_frame": "In ein Bild eingepasst",
    "png_over": "mehr, als dieser Browser zeichnen kann",
    "click_shape": "Klicke auf eine Form im Diagramm, um nur diese zu gestalten.",
    "palette_hint": "Eine Palette setzt alle Formen auf einmal. Was du "
                    "danach von Hand änderst, bleibt erhalten.",
    "shapes_hint": "Füllung und Umriss, für alle Formen dieser Art.",
    "apply_all": "Auf alle {n} anwenden: {what}", "clear": "Löschen",
    "rendering": "Wird erzeugt…",
    "png_big": "Der Browser konnte kein so großes PNG erzeugen. Nimm eine "
               "kleinere Größe oder speichere das SVG.",
    "png_fail": "Der Browser konnte das PNG nicht zeichnen. Der "
                "SVG-Download funktioniert weiterhin.",
    "png_capped": "{want}× ist mehr, als ein Browser-Canvas fasst; "
                  "das PNG wird mit {got}× gespeichert "
                  "({w} × {h} Pixel).",
    "flowchart": "Flussdiagramm",
    "r_head": "Ausführen",
    "r_run": "Starten",
    "r_stop": "Anhalten",
    "r_code": "Als Code", "r_lang_pick": "In welcher Sprache der Code geschrieben ist",
    "r_pseudo": "Pseudocode",
    "r_slowly": "Schritt für Schritt",
    "r_enter": "Eingeben",
    "r_hint": "Führt das Programm aus, aus dem das Diagramm entstanden ist: es fragt, wonach es fragt, gibt aus, was es ausgibt, und hebt die Form hervor, bei der es gerade ist. Wähle eine Sprache, um dasselbe Programm darin zu sehen.",
    "r_started": "Läuft...",
    "r_done": "Fertig.",
    "r_nothing": "Es gibt noch nichts auszuführen.",
    "r_steps": "{n} Schritte, {ms} ms.",
    "r_forever": "Das läuft viel zu lange ohne anzuhalten -- irgendwo ist eine Schleife, aus der es nie herauskommt.",
    "r_zero": "Das teilt durch null.",
    "r_unknown": "In {name} steht noch nichts.",
    "r_odd_op": "Mit {op} weiß ich nichts anzufangen.",
    "r_half": "Das liest sich nicht als Ganzes: {bit}",
    "r_back": "Zurück zum Lauf", "back": "Zurück",
    "r_by_hand": "Drücke Entwurf prüfen; besteht er, kann er hier laufen.",
    "h_runnable": "Das liest sich wie ein Programm. Du kannst es ausführen.",
    "h_no_start": "Es gibt keine Form, mit der begonnen wird.",
    "h_tangled": "Die Schleifen in diesem Entwurf kreuzen sich, er lässt sich daher nicht als Programm schreiben.",
    "h_not_a_program": "Die Wörter in diesen Formen lesen sich nicht wie ein Programm.",
    "r_build_first": "Erstelle ein Diagramm aus Pseudocode, dann "
                     "kann es hier ausgeführt werden.",
    "r_copy": "Kopieren",
    "r_copied": "Kopiert",
    "r_copy_no": "Bitte von Hand kopieren",
    "r_save_code": "Speichern",
    "r_pseudo_only": "Wähle Python, Java, C# oder JavaScript, um den Code zu sehen.",
    # ---- wo ein Lauf schiefging, und was das Lesen übergehen musste
    "r_at": "Zeile {line}",
    "r_show_line": "Zeig mir die Zeile, aus der das kommt",
    "r_in_mod": "in {name}, aufgerufen aus Zeile {line}",
    "r_in_mod_only": "in {name}",
    "r_mean": "Meintest du {name}?",
    "r_unknown_fn": "Es gibt kein Modul und keine Funktion namens {name}.",
    "r_odd_here": "Mit {bit} habe ich hier nicht gerechnet.",
    "r_empty_expr": "Hier steht nichts, woraus sich das ergeben könnte.",
    "r_left_over": "Am Ende bleibt {bit} übrig, ohne etwas, woran es gehört.",
    "r_open_quote": "Dieser Text wird nie geschlossen -- ein Anführungszeichen fehlt.",
    "r_open_bracket": "Diese Klammer wird geöffnet und nie geschlossen.",
    "r_shut_bracket": "Diese Klammer schließt eine, die nie geöffnet wurde.",
    "r_no_idea": "Aus dieser Zeile werde ich nicht schlau, der Lauf ist darüber hinweggegangen.",
    "r_stepped_over": "Einige Zeilen wurden übergangen, das Ausgegebene ist also vielleicht nicht alles.",
    "r_too_deep": "{name} hat sich viel zu oft selbst aufgerufen -- irgendwo hört es nicht mehr auf.",
    "r_args": "{name} verlangt {want} und hat {got} bekommen.",
    "r_no_main": "Hier gibt es keinen Hauptablauf, der Lauf hat also in {name} begonnen.",
    "w_head": "Einen Blick wert",
    "w_found": "{n} zum Anschauen im Pseudocode:",
    "w_open_if": "Zeile {line}: Dieses If wird nie geschlossen, alles darunter steht also darin. Setz ein End If dorthin, wo es aufhören soll.",
    "w_open_loop": "Zeile {line}: Diese Schleife wird nie geschlossen, alles darunter dreht sich mit. Setz ein End While dorthin, wo sie aufhören soll.",
    "w_open_for": "Zeile {line}: dieses For wird nie geschlossen, also dreht sich alles darunter mit. Setz ein End For dorthin, wo es aufhören soll.",
    "w_open_select": "Zeile {line}: Dieses Select wird nie geschlossen. Setz ein End Select dorthin, wo es aufhören soll.",
    "w_no_if": "Zeile {line}: End If, aber es ist kein If offen, das es schließen könnte.",
    "w_no_loop": "Zeile {line}: Das schließt eine Schleife, aber es ist keine offen.",
    "w_no_select": "Zeile {line}: End Select, aber es ist kein Select offen, das es schließen könnte.",
    "w_do_no_test": "Zeile {line}: Dieses Do bekommt nie eine Bedingung, es liefe also ewig. Schließ es mit Until ... oder Loop While ...",
    "w_until_alone": "Zeile {line}: Until, aber darüber steht kein Do und kein Repeat, das es beenden könnte.",
    "w_mend_change": "{word} in {instead} ändern",
    "w_mend_drop": "Zeile {line} entfernen",
    "w_mend_insert": "{text} in Zeile {line} einsetzen",
    "w_mend_tip": "Doppelklick, um das zu beheben",
    "n_rect": "Rechteck",
    "an_arrow": "Pfeil",
    "word_on_it": "Wort daran",
    "thickness": "Dicke",
    "color_of_it": "Farbe",
    "dashed": "Gestrichelt",
    "with_head": "Spitze",
    "turn_it_round": "Umdrehen",
    "m_type": "Hineinschreiben",
    "m_copy": "Noch eins",
    "c_fill": "Füllfarbe", "c_line": "Randfarbe", "c_words": "Textfarbe",
    "c_clear": "Kein eigener Stil",
    "m_turn": "90° drehen",
    "m_solid": "Durchgezogen",
    "m_no_word": "Kein Wort",
    "m_fit": "Auf den Bildschirm passen",
    "f_save": "In eine Datei speichern",
    "f_open": "Dokument öffnen",
    "f_not_ours": "Das ist eine JSON-Datei, aber kein hier gespeicherter Entwurf.",
    "f_opened": "{name} geöffnet.",
    "f_empty": "Darin steht nichts.",
    "dl_copy": "Diagramm kopieren",
    "dl_copied": "Kopiert",
    "dl_copy_no": "Dieser Browser lässt eine Seite kein Bild in die "
                  "Zwischenablage legen. Lade es stattdessen herunter.",
    "l_copy": "Link dazu kopieren",
    "l_copied": "Link kopiert",
    "l_copy_no": "Dieser Browser hat ihn nicht kopiert. Nimm ihn aus der "
                 "Adresszeile.",
    "l_opened": "Aus einem Link geöffnet.",
    "l_long": "Dieser Link ist {n} Zeichen lang. Mail- und Chat-Programme "
              "kürzen lange Links, und ein gekürzter Link öffnet nichts "
              "— schick lieber die Datei.",
    "l_bad": "Dieser Link enthält kein Diagramm, das diese Seite lesen kann.",
    "sv_tab": "Zwischenstände",
    "sv_about": "Behält das Diagramm, den Lauf und die Stelle, an der er "
                "war, hier in diesem Browser. Platz ist für {n}.",
    "sv_save": "Fortschritt speichern",
    "sv_saved": "Gespeichert.",
    "sv_full": "Alle {n} sind belegt. Überschreibe einen oder lösche einen, "
               "um Platz zu machen.",
    "sv_nothing": "Auf der Seite gibt es noch nichts zu speichern.",
    "sv_no_room": "Der Browser wollte es nicht behalten: sein Speicher ist "
                  "voll oder ausgeschaltet.",
    "sv_empty": "Leer",
    "sv_load": "Laden",
    "sv_over": "Überschreiben",
    "sv_over_ask": "Das, was jetzt auf der Seite ist, an seine Stelle setzen?",
    "sv_over_yes": "Überschreiben",
    "sv_del_ask": "Diesen Stand endgültig löschen?",
    "sv_today": "Heute",
    "sv_st_none": "Noch nicht ausgeführt",
    "sv_st_ask": "Wartet auf eine Antwort",
    "sv_st_next": "Wartet auf den nächsten Schritt",
    "sv_st_going": "Mitten in einem Lauf",
    "sv_st_over": "Lauf beendet",
    "sv_back": "Weiter, wo du aufgehört hast.",
    "sv_no_draw": "Das Diagramm wurde nicht gezeichnet, also konnte der "
                  "Lauf nicht fortgesetzt werden.",
    "sv_stop_said": "Einen Stand zu laden ersetzt das laufende Programm. "
                    "Der Lauf wird angehalten.",
    "sv_stop_yes": "Anhalten und laden",
    "held_head": "Was es gerade hält",
    "held_in": "in {name}",
    "held_shared": "Außerhalb aller Module deklariert, also für jedes Diagramm sichtbar",
    "held_none": "noch nichts",
    "held_switch": "Zeigen, was es gerade hält",
    "h_tidy": "Aufräumen",
    "h_tidy_tip": "Jede Form dorthin stellen, wo diese Seite sie zeichnen "
                  "würde — Wörter, Farben und Pfeile bleiben",
    "h_tidied": "Aufgeräumt: {n} Formen verschoben.",
    "h_tidy_none": "Hier gibt es noch nichts aufzuräumen.",
    "h_write": "Als Pseudocode",
    "h_write_tip": "Die Zeichnung als den Pseudocode schreiben, auf den sie "
                   "hinausläuft",
    "h_into_box": "In das Feld schreiben",
    "h_into_box_tip": "Das hier in das Pseudocode-Feld schreiben und dort "
                      "weiterarbeiten. Die Zeichnung bleibt, wo sie ist; "
                      "was im Feld stand, wird überschrieben.",
    "s_no": "Lass es",
    "s_stop_head": "Es läuft noch",
    "s_stop_said": "Ein neues Diagramm ersetzt das Programm, das gerade "
                   "läuft. Der Lauf wird abgebrochen.",
    "s_stop_yes": "Abbrechen und zeichnen",
    "n_roundrect": "Abgerundeter Kasten",
    "n_offpage": "Andere Seite", "n_loop": "Schleifengrenze", "n_parallel": "Nebeneinander",
    "n_text": "Text", "n_actor": "Person", "n_callout": "Sprechblase",
    "n_cube": "Würfel", "n_step": "Schritt", "n_table": "Tabelle",
    "n_stored": "Intern gespeichert", "n_cloud": "Cloud",
    "n_card": "Karte",
    "n_note": "Notiz",
    "n_docs": "Seiten",
    "n_manual": "Handeingabe",
    "n_screen": "Bildschirm",
    "n_arrow": "Pfeil",
    "n_io_back": "Parallelogramm andersherum",
    "n_oval": "Oval",
    "n_io": "Parallelogramm",
    "n_diamond": "Raute",
    "n_hex": "Sechseck",
    "n_sub": "Kasten mit Balken",
    "n_trap": "Trapez",
    "n_doc": "Dokument",
    "n_store": "Trommel",
    "n_delay": "Warten",
    "n_circle": "Kreis",
    "shapes_for": "Form je Art",
    "shapes_for_hint": "Welche Form für welche Art von Schritt gezeichnet wird. Was der Schritt bedeutet, ändert sich nicht.",
    "size": "Größe",
    "width": "Breite",
    "height": "Höhe",
    "turn": "Drehen",
    "fit_words": "An den Text anpassen",
    "colors_here": "Farben",
    "odd_shape": "{pair} lässt sich nicht zeichnen -- siehe --help.",
    "mode_code": "Aus Pseudocode",
    "mode_hand": "Von Hand",
    "add_shape": "Form hinzufügen",
    "hand_hint": "Formen verschieben. Eine anklicken, dann Verbinden, dann die Form anklicken, zu der es weitergeht.",
    "words_in": "Text in der Form",
    "connect": "Verbinden",
    "connect_now": "Jetzt die Form anklicken, zu der es geht.",
    "goes_to": "Geht zu",
    "nothing_yet": "noch nichts",
    "delete": "Löschen",
    "check": "Entwurf prüfen",
    "checked_good": "Der Entwurf trägt: ein Start, alle Formen erreichbar, und jeder Weg endet an einem Ende.",
    "problems": "{n} zum Ansehen",
    "pick_shape": "Klicke eine Form an, um sie zu beschriften, zu verschieben oder zu verbinden.",
    "as_chart": "Diagramm",
    "untitled": "Ohne Titel",
    "p_no_start": "Nichts beginnt den Ablauf: in jede Form führt etwas hinein.",
    "p_many_starts": "In {n} Formen führt nichts hinein. Ein Diagramm beginnt an einer Stelle.",
    "p_start_kind": "Die Form, mit der alles anfängt, sollte ein Oval sein.",
    "p_no_end": "Es gibt kein Ende: kein Oval, an dem der Ablauf aufhört.",
    "p_unreached": "Zu dieser Form führt nichts.",
    "p_dead_end": "Aus dieser Form führt nichts heraus, und sie ist kein Ende.",
    "p_decision_out": "Eine Entscheidung braucht zwei Ausgänge, einen je Antwort. Diese hat {n}.",
    "p_one_out": "Diese Form hat {n} Ausgänge. Nur eine Entscheidung darf mehr als einen haben.",
    "p_same_labels": "Beide Ausgänge dieser Entscheidung sagen dasselbe.",
    "p_no_label": "Ein Ausgang einer Entscheidung braucht ein Wort.",
    "p_trapped": "Kommt der Ablauf hierher, erreicht er nie ein Ende.",
    "p_empty": "In dieser Form steht nichts.",
    "p_overlap": "Diese Form liegt auf einer anderen.",
    "p_alone": "Diese Form ist mit nichts verbunden.",
    "p_line_through": "Eine Linie läuft mitten durch diese Form. Verschiebe eine von beiden etwas.",
    "side_chart": "Diagramm", "side_colors": "Stil", "hide_panel": "Bereich ausblenden", "show_panel": "Bereich einblenden",
    "theme": "Hell oder dunkel", "theme_auto": "Auto", "theme_light": "Hell", "theme_dark": "Dunkel",
    "puzzles": "Rätsel",
    "pz_one": "Rätsel {n}",
    "pz_head": "Rätsel",
    "pz_l1": "Finde den Fehler",
    "pz_l2": "Bring es zum Laufen",
    "pz_l3": "Bau es",
    "pz_check": "Prüfen",
    "pz_right": "Gelöst.",
    "pz_wrong": "Noch nicht. Bei {give} kam {said}.",
    "pz_next": "Nächstes Rätsel", "pz_next_level": "Nächste Stufe",
    "pz_job": "Was es tun soll", "pz_now": "Was es jetzt tut",
    "pz_reset": "Neu anfangen", "pz_all": "Alle Rätsel",
    "pz_broke": "Es brach vorher ab. Es bekam {give}.",
    "pz_none": "Es gibt noch nichts zu prüfen.",
    "pz_locked": "Löse noch {n}, um diese zu öffnen",
    "pz_done": "{done} von {all} gelöst",
    "pz_nothing": "(nichts)",
    "pz_brief": "Die Aufgabe",
    "z_greet_b": "Es grüßt, bevor es gefragt hat. Erst fragen, dann grüßen.",
    "z_range_b": "1 bis 9 soll im Bereich liegen. Im Moment jede Zahl.",
    "z_double_b": "Es soll das Doppelte der eingegebenen Zahl zeigen.",
    "z_order_b": "Es soll nur die Endsumme 6 zeigen, nichts auf dem Weg dorthin.",
    "z_until_b": "Es soll 1, 2, 3 zählen und dann aufhören.",
    "z_nested_b": "Zwei Reihen zu zweit: 1, 2, 2, 4. Die innere Schleife ist eins zu kurz.",
    "z_param_b": "show() zeigt den Buchstaben x statt der übergebenen Zahl.",
    "z_many_b": "Von fünf eingegebenen Zahlen soll es sagen, wie viele über 10 sind.",
    "z_divide_b": "Es addiert vier Zahlen, also geht der Mittelwert durch vier, nicht fünf.",
    "z_sign_b": "Über null ist positiv, darunter negativ, und null ist „zero“.",
    "z_twice_b": "Es soll das Wort zweimal zeigen.",
    "z_minus_b": "Es soll die zweite Zahl von der ersten abziehen.",
    "z_early_b": "Es zeigt die Antwort, bevor es sie berechnet hat. Es soll das Dreifache zeigen.",
    "z_never_b": "Es soll von 5 bis 1 zählen. Im Moment zeigt es gar nichts.",
    "z_odds_b": "Es soll die geraden Zahlen von 1 bis 10 addieren, zusammen 30.",
    "z_asked_b": "Es soll drei Zahlen erfragen und diese drei addieren.",
    "z_onemore_b": "Es soll 1 bis 10 addieren, zusammen 55.",
    "z_valid_b": "Es soll weiterfragen, bis die Zahl von 1 bis 10 ist, und sie dann zeigen.",
    "z_smallest_b": "Es soll die größte der vier eingegebenen Zahlen zeigen.",
    "z_short_b": "add() nimmt zwei Zahlen. Es bekommt nur eine.",
    "z_stops_b": "Es soll 5 bis 1 zeigen und dann „go“.",
    "pz_l4": "Schwerere Fehler",
    "pz_l5": "Echte Bugs",
    "z_fizz_b": "15 soll FizzBuzz sagen. Die Tests stehen in der falschen Reihenfolge.",
    "z_prime_b": "Eine Primzahl hat genau zwei Teiler. Hier gilt 1 als prim.",
    "z_digits_b": "Es soll sagen, wie viele Ziffern die Zahl hat. 7 hat eine.",
    "z_revzero_b": "Es soll die Ziffern umdrehen. Aus 123 wird 321.",
    "z_sumd_b": "Es soll die Ziffern der Zahl addieren. 123 ergibt 6.",
    "z_gridrow_b": "Drei Reihen: 1 2 3, dann 2 4 6, dann 3 6 9. Die Reihe aendert sich nie.",
    "z_tri_b": "Es soll jede Dreieckszahl unterwegs zeigen: 1, 3, 6, 10.",
    "z_lowhigh_b": "Es soll die kleinste und dann die groesste der vier Zahlen zeigen.",
    "z_starsrow_b": "Reihe eins ein Stern, Reihe zwei zwei Sterne, und so weiter.",
    "z_factloop_b": "Mal null ist null. 4 Fakultaet ist 24.",
    "z_report_b": "Fuenf Noten gehen hinein, also geht der Mittelwert durch fuenf.",
    "z_tries_b": "Drei Versuche beim Passwort, und dann gesperrt.",
    "z_discount_b": "Ueber 50 gibt zehn Prozent Rabatt, 60 soll also 54 ergeben.",
    "z_convert_b": "C nach F ist neun Fuenftel und dann plus 32. 100 C sind 212 F.",
    "z_tie_b": "Gleich viele Stimmen sollen ein Unentschieden ergeben.",
    "z_fibstep_b": "Es soll 0, 1, 1, 2, 3 zeigen. Die zwei Zahlen werden falsch herum verschoben.",
    "z_coins_b": "132 Pence sind 1 Pfund, 3 Zehner und 2 Pennies.",
    "z_score_b": "Eine richtige Antwort gibt einen Punkt, eine falsche keinen.",
    "z_sent_b": "Zahlen bis 0 getippt wird, dann der Mittelwert der Zahlen davor.",
    "z_menu0_b": "0 soll es beenden. Im Moment geht es wieder von vorn los.",
    "z_else_b": "Unter 18 wird gar nichts gesagt. Es sollte „out“ heißen.",
    "z_swap_b": "Über 10 ist groß, 10 oder weniger ist klein. Hier ist es vertauscht.",
    "z_count_b": "Es sollte von 1 bis 5 zählen.",
    "z_forever_b": "Es sollte 3, 2, 1 und dann „go“ zeigen. Im Moment hört es nie auf.",
    "z_total_b": "Es sollte 1, 2, 3 und 4 addieren und 10 zeigen.",
    "z_two_b": "Es sollte zwei Zahlen addieren und das Ergebnis zeigen.",
    "z_return_b": "twice() sollte die verdoppelte Zahl zurückgeben, damit Display sie zeigt.",
    "z_evens_b": "Es sollte nur die geraden Zahlen von 1 bis 10 zeigen.",
    "z_grade_b": "50 ist bestanden. Im Moment fällt 50 durch.",
    "e_add": "Zwei Zahlen addieren",
    "e_oddeven": "Gerade oder ungerade",
    "e_guess": "Zahl raten",
    "e_highest": "Die höchste bisher",
    "e_swap": "Zwei Zahlen tauschen",
    "e_factorial": "Eine Fakultät",
    "try_short": "Neu hier?",
    "try_go": "Beispiel ausprobieren",
    "e_double": "Mal zwei",
    "e_area": "Fläche eines Rechtecks",
    "e_bigger": "Die größere von zweien",
    "e_sumevens": "Die geraden addieren",
    "e_onetable": "Eine Malreihe",
    "e_vowel": "Vokal oder nicht",
    "e_leap": "Schaltjahr",
    "e_power": "Hoch rechnen",
    "e_backwards": "Rückwärts zählen",
    "eg_l4": "Noch schwerer",
    "eg_l5": "Größere Programme",
    "e_fizz": "Fizz und Buzz",
    "e_prime": "Ist es eine Primzahl?",
    "e_gcd": "Größter gemeinsamer Teiler",
    "e_digits": "Wie viele Ziffern",
    "e_reverse": "Die Zahl rückwärts",
    "e_sumdigits": "Ziffern addieren",
    "e_grid": "Ein Einmaleins-Gitter",
    "e_triangle": "Dreieckszahlen",
    "e_minmax": "Kleinste und größte",
    "e_stars": "Ein Dreieck aus Sternen",
    "e_report": "Ein Klassenbericht",
    "e_login": "Drei Versuche beim Passwort",
    "e_shop": "Eine Kasse mit Rabatt",
    "e_temps": "Celsius in Fahrenheit",
    "e_votes": "Stimmen zählen",
    "e_fib": "Die Fibonacci-Zahlen",
    "e_change": "Pfund, Zehner und Pennies",
    "e_quiz": "Ein Quiz mit drei Fragen",
    "e_sentinel": "Zahlen, bis 0 kommt",
    "e_picktable": "Jede Reihe, die du willst",
    "eg_head": "Beispiele",
    "eg_more": "Mehr Beispiele",
    "eg_l1": "Erste Schritte",
    "eg_l2": "Zusammensetzen",
    "eg_l3": "Weitergehen",
    "e_ask": "Fragen und zeigen",
    "e_decide": "Eine Entscheidung",
    "e_count": "Zählen",
    "e_total": "Eine laufende Summe",
    "e_while": "Eine While-Schleife",
    "e_grades": "Noten",
    "e_biggest": "Die größte von dreien",
    "e_menu": "Ein Menü",
    "e_keepasking": "Immer wieder fragen",
    "e_tables": "Einmaleins",
    "e_module": "Ein Modul",
    "e_answers": "Eine Funktion mit Rückgabe",
    "e_average": "Ein Mittelwert",
    "e_countdown": "Countdown",
    "e_password": "Ein Passwort",
    "try_one": "Neu hier? Fangen Sie mit einem davon an:",
    "eg_decision": "Eine Entscheidung", "eg_loop": "Eine Schleife", "eg_module": "Ein Modul",
    "r_pace": "Wie es läuft", "r_at_once": "Auf einmal",
    "r_by_step": "Einzeln", "r_next": "Nächster Schritt",
    "r_timed": "Im Takt des Programms",
    "chart_desc": "Flussdiagramm mit {n} Formen: {kinds}.",
    "yes_plain": "Ja", "no_plain": "Nein",
    "more_head": "Diagramm-Optionen",
    "o_words": "Sprache und Wörter",
    "o_chains": "Lange If-Ketten untereinander setzen",
    "o_shapes": "Die Formen", "o_paper": "Abstände und Papier",
    "o_for": "For-Schleifen", "o_for_wide": "Ausgeschrieben", "o_for_hex": "Ein Sechseck",
    "o_everyout": "Ein Symbol für jede Ausgabe",
    "o_roomy": "Größere Abstände",
    "o_columns": "Hohes Diagramm in Spalten umbrechen",
    "o_steady": "Jedes Mal dieselbe Zeichnung",
    "more": "Optionen", "more_tip": "Weitere Diagramm-Optionen",
    "decide": "Entscheidungen",
    "undo": "Rückgängig", "redo": "Wiederholen",
    "settings": "Einstellungen", "appearance": "Darstellung", "panel_side": "Seite des Panels",
    "side_left": "Links", "side_right": "Rechts", "full_screen": "Vollbild",
    "full_on": "Bildschirm füllen", "full_off": "Vollbild verlassen",
    "no_full": "Dieser Browser kennt kein Vollbild.",
    "p_ink": "Tinte", "p_classic": "Klassisch", "p_slate": "Schiefer",
    "p_meadow": "Wiese", "p_sunset": "Abendrot", "p_night": "Nacht",
    "pseudocode": "Pseudocode", "title": "Titel", "your_name": "Dein Name",
    "code_big": "Bildschirm füllen", "code_small": "Zurück zum Panel", "done": "Fertig",
    "code_esc": "Esc zum Schließen", "code_lines": "{n} Zeilen",
    "code_ask": "{name} eingeben: ",
    "code_shares": "was das Programm teilt",
    "c_head": "Code", "c_write": "Den Code schreiben",
    "c_one": "In einer Datei", "c_apart": "Eine Datei je Diagramm",
    "c_files_tip": "Ob er als eine Datei oder als eine Datei je Diagramm herauskommt",
    "c_one_chart": "Dieses Programm ist ein Diagramm und wird eine Datei.",
    "c_files": "{n} Dateien", "c_save_all": "Alle speichern",
    "c_zipped": "{n} Dateien, in einer .zip",
    "shape": "Form",
    "language": "Sprache", "key_switch": "Legende", "tint_switch": "Farbtöne",
    "build": "Diagramm zeichnen", "drawing": "Wird gezeichnet…",
    "no_code": "Es gibt noch keinen Pseudocode zum Zeichnen.",
    "failed": "Das ließ sich nicht zeichnen.",
    "not_answering": "Das Studio antwortet nicht ({err}).",
    "empty_chart": "Füge links deinen Pseudocode ein und klicke auf "
                   "Zeichnen.",
    "shape_auto": "Automatisch", "shape_square": "Quadratisch",
    "shape_wide": "Breit 16:9", "shape_page": "Seite", "shape_tall": "Hoch",
    "already": "Schon da {path}",
    "copied": "{n} Dateien nach {dir} kopiert",
    "wrote": "Geschrieben {path}",
    "open_this": "<- diese hier öffnen: sie zeigt das Diagramm und hat "
                 "die Download-Links",
    "style_seed": "Stil-Startwert {seed} (mit --seed {seed} kommt genau "
                  "dieses Bild wieder)",
    "nothing": "Kein Pseudocode angegeben -- nichts zu zeichnen.",
    "studio_at": "Das Flussdiagramm-Studio läuft auf {url}",
    "leave_open": "Lass dieses Fenster offen, solange du es benutzt; "
                  "Strg+C beendet es.",
    "stopped": "Studio beendet.",
    "site_done": "Dieser Ordner ist eine Website. Lade ihn zu GitHub "
                 "Pages hoch (oder zu einem anderen Datei-Host); die "
                 "Schritte stehen in {dir}/README.md.",
    "starting": "Python startet im Browser…",
    "ready": "Fertig.",
    "boot_failed": "Python konnte in diesem Browser nicht starten ({err}).",
}

speaks("de", "Deutsch", DE)
