"""Every word it says, in Spanish."""
from ..words.lookup import speaks

ES = {
    "start": "Inicio", "end": "Fin", "ret": "Retornar",
    "yes": "Verdadero", "no": "Falso", "again": "¿otra vez?",
    "key_oval": "Inicio / Fin", "key_rect": "Proceso",
    "key_io": "Entrada / Salida", "key_diamond": "Decisión",
    "key_hex": "Bucle", "key_sub": "Llamar a un módulo",
    "palette": "Paleta", "shapes": "Formas",
    # ---- the Style side: the words, the highlighter, the borders
    "t_head": "Texto", "t_face": "Tipo de letra",
    "t_sans": "Simple", "t_serif": "Libro",
    "t_mono": "Código", "t_hand": "A mano",
    "t_size": "Tamaño", "t_smaller": "Más pequeño",
    "t_bigger": "Más grande", "t_bold": "Negrita",
    "t_italic": "Cursiva", "t_under": "Subrayado",
    "t_strike": "Tachado", "t_color": "Color",
    "t_mark": "Resaltado", "t_mark_none": "Sin resaltado",
    "cp_sat": "Saturación", "cp_bright": "Brillo",
    "cp_recent": "Recientes", "cp_code": "Código de color",
    "t_mark_own": "Otro color", "m_yellow": "Amarillo",
    "m_green": "Verde", "m_pink": "Rosa",
    "m_blue": "Azul", "m_orange": "Naranja",
    "t_weight": "Grosor de línea", "t_thin": "Fina",
    "t_normal": "Normal", "t_thick": "Gruesa",
    "t_border": "Borde", "t_dashed": "Borde discontinuo",
    "t_copy_look": "Copiar estilo", "t_paste_look": "Pegar estilo",
    "t_size_list": "Elegir un tamaño",
    "selected": "Forma seleccionada", "rest": "Líneas y papel",
    "fill": "Relleno", "outline": "Contorno", "text": "Texto",
    "paper": "Papel", "grid": "Cuadrícula",
    "show_grid": "Mostrar la cuadrícula",
    "lines": "Líneas y flechas", "reset": "Restaurar todo el estilo",
    "download": "Descargar", "dl_size": "Tamaño",
    "files": "Archivos", "f_work_head": "Tu trabajo",
    "dl_svg": "Descargar SVG", "dl_png": "Descargar PNG", "panel": "Panel",
    "print_it": "Imprimir el diagrama",
    "print_head": "Imprimir",
    "print_go": "Imprimir…",
    "print_paper": "Papel",
    "print_wide": "Apaisado",
    "print_fit": "Ajustar a una página",
    "print_note": "Se imprime simple: sin colores, solo líneas y palabras. Qué impresora y cuántas copias lo pregunta tu navegador — una página no puede preguntarlo.",
    "panel_tip": "Mostrar u ocultar el panel",
    "png_tip": "Tamaño del PNG",
    "fit": "Ajustar", "actual": "Real", "zoom_in": "Acercar",
    "slide_left": "Izquierda", "slide_right": "Derecha", "slide_up": "Arriba", "slide_down": "Abajo",
    "hold_locked": "Fijo", "hold_loose": "Libre",
    "lock_tip": "Mantener el diagrama en su sitio, desplazándose dentro del área",
    "loose_tip": "Arrastra el diagrama a donde quieras; siempre queda una esquina a la vista",
    "zoom_out": "Alejar", "pixels": "píxeles",
    "dl_scale": "Veces el tamaño dibujado",
    "dl_frame": "Ajustado dentro de una imagen",
    "png_over": "más de lo que este navegador puede dibujar",
    "click_shape": "Haz clic en una forma del diagrama para dar estilo solo a esa.",
    "palette_hint": "Una paleta cambia todas las formas a la vez. Lo que "
                    "cambies a mano después se conserva.",
    "shapes_hint": "Relleno y contorno, para todas las formas de ese tipo.",
    "apply_all": "Aplicar a las {n} formas: {what}", "clear": "Borrar",
    "rendering": "Generando…",
    "png_big": "El navegador no pudo crear un PNG tan grande. Prueba con "
               "un tamaño menor o guarda el SVG.",
    "png_fail": "El navegador no pudo dibujar el PNG. La descarga del SVG "
                "sigue funcionando.",
    "png_capped": "{want}× supera lo que admite el lienzo del "
                  "navegador, así que el PNG se guarda a {got}× "
                  "({w} × {h} píxeles).",
    "flowchart": "Diagrama de flujo",
    "r_head": "Ejecutar",
    "r_run": "Ejecutar",
    "r_stop": "Detener",
    "r_code": "Como código", "r_lang_pick": "En qué lenguaje está escrito el código",
    "r_pseudo": "Pseudocódigo",
    "r_slowly": "Paso a paso",
    "r_enter": "Entrar",
    "r_hint": "Ejecuta el programa del que salió el diagrama: pide lo que le pide a una persona, muestra lo que muestra y resalta la forma en la que está. Elige un lenguaje para ver el mismo programa escrito en él.",
    "r_started": "Ejecutando...",
    "r_done": "Terminado.",
    "r_nothing": "Todavía no hay nada que ejecutar.",
    "r_steps": "{n} pasos, {ms} ms.",
    "r_forever": "Lleva demasiado tiempo sin parar: en algún sitio hay un bucle del que nunca sale.",
    "r_zero": "Eso divide entre cero.",
    "r_unknown": "Todavía no se ha puesto nada en {name}.",
    "r_odd_op": "No sé qué hacer con {op}.",
    "r_half": "Esto no se lee como algo completo: {bit}",
    "r_back": "Volver a la ejecución", "back": "Atrás",
    "r_by_hand": "Pulsa Comprobar el diseño; si pasa, se puede ejecutar aquí.",
    "h_runnable": "Se lee como un programa. Ya puedes ejecutarlo.",
    "h_no_start": "No hay ninguna forma por la que empezar.",
    "h_tangled": "Los bucles de este diseño se cruzan, así que no se puede escribir como un programa.",
    "h_not_a_program": "Las palabras de estas formas no se leen como un programa.",
    "r_build_first": "Construye un diagrama desde pseudocódigo y "
                     "podrá ejecutarse aquí.",
    "r_copy": "Copiar",
    "r_copied": "Copiado",
    "r_copy_no": "Cópialo a mano",
    "r_save_code": "Guardar",
    "r_file": "{name} salida",
    "r_pseudo_only": "Elige Python, Java, C# o JavaScript para ver el código.",
    # ---- dónde falló la ejecución, y qué tuvo que disimular la lectura
    "r_at": "Línea {line}",
    "r_show_line": "Muéstrame la línea de la que viene",
    "r_in_mod": "dentro de {name}, llamado desde la línea {line}",
    "r_in_mod_only": "dentro de {name}",
    "r_mean": "¿Querías decir {name}?",
    "r_unknown_fn": "No hay ningún módulo ni función que se llame {name}.",
    "r_odd_here": "No esperaba {bit} aquí.",
    "r_empty_expr": "Aquí no hay nada de lo que sacarlo.",
    "r_left_over": "Sobra {bit} al final de esto, sin nada a lo que unirse.",
    "r_open_quote": "Este texto no se cierra nunca: falta una comilla.",
    "r_open_bracket": "Este paréntesis se abre y no se cierra.",
    "r_shut_bracket": "Este paréntesis cierra uno que nunca se abrió.",
    "r_no_idea": "No consigo entender esta línea, así que la ejecución pasó de largo.",
    "r_stepped_over": "Se saltaron algunas líneas, así que lo impreso puede no ser todo.",
    "r_too_deep": "{name} se ha llamado a sí mismo demasiadas veces: en alguna parte no deja de llamarse.",
    "r_args": "{name} pide {want} y le han dado {got}.",
    "r_no_main": "Aquí no hay flujo principal, así que la ejecución empezó en {name}.",
    "w_head": "Merece un vistazo",
    "w_found": "{n} para mirar en el pseudocódigo:",
    "w_open_if": "Línea {line}: este If no se cierra nunca, así que todo lo de abajo queda dentro. Añade un End If donde deba terminar.",
    "w_open_loop": "Línea {line}: este bucle no se cierra nunca, así que todo lo de abajo da vueltas con él. Añade un End While donde deba terminar.",
    "w_open_for": "Línea {line}: este For nunca se cierra, así que todo lo que hay debajo da vueltas con él. Añade un End For donde deba terminar.",
    "w_open_select": "Línea {line}: este Select no se cierra nunca. Añade un End Select donde deba terminar.",
    "w_no_if": "Línea {line}: End If, pero no hay ningún If abierto que cerrar.",
    "w_no_loop": "Línea {line}: esto cierra un bucle, pero no hay ningún bucle abierto.",
    "w_no_select": "Línea {line}: End Select, pero no hay ningún Select abierto que cerrar.",
    "w_do_no_test": "Línea {line}: a este Do no se le da ninguna condición, así que daría vueltas para siempre. Termiñalo con Until ... o Loop While ...",
    "w_until_alone": "Línea {line}: Until, pero no hay ningún Do ni Repeat encima al que cerrar.",
    "w_mend_change": "Cambiar {word} por {instead}",
    "w_mend_drop": "Quitar la línea {line}",
    "w_mend_insert": "Poner {text} en la línea {line}",
    "w_mend_tip": "Doble clic para arreglarlo",
    "n_rect": "Rectángulo",
    "an_arrow": "Flecha",
    "word_on_it": "Palabra en ella",
    "thickness": "Grosor",
    "color_of_it": "Color",
    "dashed": "Discontinua",
    "with_head": "Punta",
    "turn_it_round": "Invertir",
    "m_type": "Escribir dentro",
    "m_copy": "Duplicar",
    "c_fill": "Color de relleno", "c_line": "Color del borde", "c_words": "Color del texto",
    "c_clear": "Sin estilo propio",
    "m_turn": "Girar 90°",
    "m_solid": "Continua",
    "m_no_word": "Sin palabra",
    "m_fit": "Ajustar a la pantalla",
    "f_save": "Guardar en un archivo",
    "f_open": "Abrir un documento",
    "f_not_ours": "Es un archivo JSON, pero no un diseño guardado desde aquí.",
    "f_opened": "Se abrió {name}.",
    "f_empty": "Ese no tiene nada escrito.",
    "dl_copy": "Copiar el diagrama",
    "dl_copied": "Copiado",
    "dl_copy_no": "Este navegador no deja que una página ponga una imagen "
                  "en el portapapeles. Descárgala en su lugar.",
    "l_copy": "Copiar un enlace a esto",
    "l_copied": "Enlace copiado",
    "l_copy_no": "Este navegador no lo copió. Tómalo de la barra de "
                 "direcciones.",
    "fd_head": "Dónde se guarda",
    "fd_browser": "En las descargas de tu navegador.",
    "fd_in": "En la carpeta {name}.",
    "fd_pick": "Elegir una carpeta",
    "fd_pick_tip": "Elige una carpeta, o crea una nueva en la ventana que se "
                   "abre. Todo lo que guardes desde aquí irá directamente "
                   "a ella.",
    "fd_off": "Volver a las descargas",
    "fd_cannot": "Este navegador solo guarda en sus descargas. Chrome o Edge "
                 "en una computadora pueden guardar en la carpeta que elijas.",
    "fd_saved": "{name} guardado en {folder}",
    "fd_fell": "{folder} no lo aceptó, así que fue a tus descargas.",
    "l_opened": "Abierto desde un enlace.",
    "l_long": "Ese enlace tiene {n} caracteres. El correo y los chats cortan "
              "los enlaces largos, y un enlace cortado no abre nada: mejor "
              "envía el archivo.",
    "l_bad": "Ese enlace no lleva ningún diagrama que esta página pueda leer.",
    "sv_tab": "Progreso guardado",
    "sv_about": "Guarda el diagrama, la ejecución y el punto al que había "
                "llegado, aquí en este navegador. Hay sitio para {n}.",
    "sv_save": "Guardar el progreso",
    "sv_saved": "Guardado.",
    "sv_full": "Los {n} están ocupados. Guarda encima de uno, o borra uno "
               "para hacer sitio.",
    "sv_nothing": "Todavía no hay nada en la página que guardar.",
    "sv_no_room": "El navegador no quiso guardarlo: su almacenamiento está "
                  "lleno o desactivado.",
    "sv_empty": "Vacío",
    "sv_load": "Cargar",
    "sv_over": "Guardar encima",
    "sv_over_ask": "¿Poner lo que hay ahora en la página en lugar de este?",
    "sv_over_yes": "Guardar encima",
    "sv_del_ask": "¿Borrar este guardado para siempre?",
    "sv_today": "Hoy",
    "sv_st_none": "Sin ejecutar",
    "sv_st_ask": "Esperando una respuesta",
    "sv_st_next": "Esperando el siguiente paso",
    "sv_st_going": "A mitad de una ejecución",
    "sv_st_over": "Ejecución terminada",
    "sv_back": "Sigue donde lo dejaste.",
    "sv_moved": "Este guardado ya no encaja con el programa, así que no se "
                "pudo retomar la ejecución.",
    "sv_lost": "No se pudo leer el programa de este guardado desde el "
               "almacenamiento del navegador.",
    "sv_no_draw": "El diagrama no se dibujó, así que la ejecución no pudo "
                  "retomarse.",
    "sv_stop_said": "Cargar un guardado sustituye al programa que se está "
                    "ejecutando. La ejecución se detendrá.",
    "sv_stop_yes": "Detener y cargar",
    "held_head": "Lo que tiene guardado",
    "held_in": "en {name}",
    "held_shared": "Declarado fuera de todo módulo, así que lo ve cada diagrama",
    "held_none": "nada todavía",
    "held_switch": "Mostrar lo que tiene guardado",
    "h_tidy": "Ordenar",
    "h_tidy_tip": "Colocar cada figura donde esta página la dibujaría, "
                  "conservando las palabras, los colores y las flechas",
    "h_tidied": "Ordenado: {n} figuras movidas.",
    "h_tidy_none": "Todavía no hay nada que ordenar aquí.",
    "h_write": "Como pseudocódigo",
    "h_write_tip": "Escribir el dibujo como el pseudocódigo al que equivale",
    "h_into_box": "Ponerlo en el cuadro",
    "h_into_box_tip": "Escribir esto en el cuadro de pseudocódigo y "
                      "seguir ahí. El dibujo se queda donde está; lo que "
                      "hubiera en el cuadro se sobrescribe.",
    "s_no": "Déjalo",
    "s_stop_head": "Todavía se está ejecutando",
    "s_stop_said": "Dibujar un diagrama nuevo reemplaza el programa que se "
                   "está ejecutando. La ejecución se detendrá.",
    "s_stop_yes": "Detener y dibujar",
    "n_roundrect": "Caja redondeada",
    "n_offpage": "Fuera de página", "n_loop": "Límite de bucle", "n_parallel": "En paralelo",
    "n_text": "Texto", "n_actor": "Persona", "n_callout": "Bocadillo",
    "n_cube": "Cubo", "n_step": "Paso", "n_table": "Tabla",
    "n_stored": "Almacenado dentro", "n_cloud": "Nube",
    "n_card": "Tarjeta",
    "n_note": "Nota",
    "n_docs": "Páginas",
    "n_manual": "Entrada manual",
    "n_screen": "Pantalla",
    "n_arrow": "Flecha",
    "n_io_back": "Paralelogramo al revés",
    "n_oval": "Óvalo",
    "n_io": "Paralelogramo",
    "n_diamond": "Rombo",
    "n_hex": "Hexágono",
    "n_sub": "Caja con barras",
    "n_trap": "Trapecio",
    "n_doc": "Documento",
    "n_store": "Cilindro",
    "n_delay": "Espera",
    "n_circle": "Círculo",
    "shapes_for": "Forma de cada tipo",
    "shapes_for_hint": "Qué forma se dibuja para cada tipo de paso. Lo que significa el paso no cambia.",
    "size": "Tamaño",
    "width": "Ancho",
    "height": "Alto",
    "turn": "Girar",
    "fit_words": "Ajustar al texto",
    "colors_here": "Colores",
    "odd_shape": "No se puede dibujar {pair}; mira --help.",
    "mode_code": "Desde pseudocódigo",
    "mode_hand": "A mano",
    "add_shape": "Añadir una forma",
    "hand_hint": "Arrastra las formas. Haz clic en una, luego en Conectar, y después en la forma a la que sigue el flujo.",
    "words_in": "Texto de la forma",
    "connect": "Conectar",
    "connect_now": "Ahora haz clic en la forma a la que va.",
    "goes_to": "Va a",
    "nothing_yet": "nada todavía",
    "delete": "Eliminar",
    "check": "Comprobar el diseño",
    "checked_good": "El diseño funciona: un solo Inicio, todas las formas alcanzables y todos los caminos terminan en un Fin.",
    "problems": "{n} cosas que revisar",
    "pick_shape": "Haz clic en una forma para escribir en ella, moverla o unirla a otra.",
    "as_chart": "Diagrama",
    "untitled": "Sin título",
    "p_no_start": "Nada inicia el flujo: todas las formas tienen algo que llega a ellas.",
    "p_many_starts": "{n} formas no tienen nada que llegue a ellas. Un diagrama empieza en un solo sitio.",
    "p_start_kind": "La forma por la que todo empieza debería ser un óvalo.",
    "p_no_end": "No hay Fin: ningún óvalo donde el flujo se detenga.",
    "p_unreached": "Nada lleva a esta forma.",
    "p_dead_end": "No sale nada de esta forma y no es un Fin.",
    "p_decision_out": "Una decisión necesita dos salidas, una por respuesta. Esta tiene {n}.",
    "p_one_out": "Esta forma tiene {n} salidas. Solo una decisión puede tener más de una.",
    "p_same_labels": "Las dos salidas de esta decisión dicen lo mismo.",
    "p_no_label": "Una salida de una decisión necesita una palabra.",
    "p_trapped": "Si el flujo llega aquí, nunca podrá llegar a un Fin.",
    "p_empty": "Esta forma no tiene nada escrito.",
    "p_overlap": "Esta forma está encima de otra.",
    "p_alone": "Esta forma no está unida a nada.",
    "p_line_through": "Una línea atraviesa esta forma. Mueve un poco alguna de las dos.",
    "side_chart": "Diagrama", "side_colors": "Estilo", "hide_panel": "Ocultar el panel", "show_panel": "Mostrar el panel",
    "theme": "Claro u oscuro", "theme_auto": "Auto", "theme_light": "Claro", "theme_dark": "Oscuro",
    "puzzles": "Retos",
    "pz_one": "Reto {n}",
    "pz_head": "Retos",
    "pz_l1": "Encuentra el fallo",
    "pz_l2": "Haz que funcione",
    "pz_l3": "Constrúyelo",
    "pz_check": "Comprobar",
    "pz_right": "Resuelto.",
    "pz_wrong": "Todavía no. Con {give} dijo {said}.",
    "pz_next": "Siguiente reto", "pz_next_level": "Siguiente nivel",
    "pz_job": "Lo que debe hacer", "pz_now": "Lo que hace ahora",
    "pz_reset": "Empezar de nuevo", "pz_all": "Todos los retos",
    "pz_broke": "Se paró antes de terminar. Le dieron {give}.",
    "pz_none": "Aún no hay nada que comprobar.",
    "pz_locked": "Resuelve {n} más para abrir estos",
    "pz_done": "{done} de {all} resueltos",
    "pz_nothing": "(nada)",
    "pz_brief": "El reto",
    "z_greet_b": "Saluda antes de preguntar a quién. Primero preguntar, luego saludar.",
    "z_range_b": "Del 1 al 9 debería estar en el rango. Ahora lo está cualquier número.",
    "z_double_b": "Debería mostrar el doble del número que le dan.",
    "z_order_b": "Debería mostrar el total final, 6, y nada por el camino.",
    "z_until_b": "Debería contar 1, 2, 3 y luego parar.",
    "z_nested_b": "Dos filas de dos: 1, 2, 2, 4. Al bucle interior le falta uno.",
    "z_param_b": "show() muestra la letra x en vez del número que le pasaron.",
    "z_many_b": "De los cinco números escritos, debería decir cuántos pasan de 10.",
    "z_divide_b": "Suma cuatro números, así que el promedio es entre cuatro, no cinco.",
    "z_sign_b": "Sobre cero es positivo, debajo negativo, y cero es “zero”.",
    "z_twice_b": "Debería mostrar la palabra dos veces.",
    "z_minus_b": "Debería restar el segundo número del primero.",
    "z_early_b": "Muestra la respuesta antes de calcularla. Debería mostrar el triple.",
    "z_never_b": "Debería contar de 5 a 1. Ahora no muestra nada.",
    "z_odds_b": "Debería sumar los pares del 1 al 10, que dan 30.",
    "z_asked_b": "Debería pedir tres números y sumar esos tres.",
    "z_onemore_b": "Debería sumar del 1 al 10, que dan 55.",
    "z_valid_b": "Debería seguir preguntando hasta que sea del 1 al 10, y luego mostrarlo.",
    "z_smallest_b": "Debería mostrar el mayor de los cuatro números escritos.",
    "z_short_b": "add() toma dos números. Solo le dan uno.",
    "z_stops_b": "Debería mostrar de 5 a 1 y luego “go”.",
    "pz_l4": "Fallos mas dificiles",
    "pz_l5": "Errores de verdad",
    "z_fizz_b": "15 debe decir FizzBuzz. Las pruebas estan en mal orden.",
    "z_prime_b": "Un primo tiene exactamente dos divisores. Aqui el 1 cuenta como primo.",
    "z_digits_b": "Debe decir cuantas cifras tiene el numero. El 7 tiene una.",
    "z_revzero_b": "Debe dar la vuelta a las cifras. 123 pasa a 321.",
    "z_sumd_b": "Debe sumar las cifras del numero. 123 da 6.",
    "z_gridrow_b": "Tres filas: 1 2 3, luego 2 4 6, luego 3 6 9. La fila nunca cambia.",
    "z_tri_b": "Debe mostrar cada numero triangular: 1, 3, 6, 10.",
    "z_lowhigh_b": "Debe mostrar el menor y luego el mayor de los cuatro numeros.",
    "z_starsrow_b": "Fila uno una estrella, fila dos dos estrellas, y asi.",
    "z_factloop_b": "Cualquier cosa por cero es cero. 4 factorial es 24.",
    "z_report_b": "Entran cinco notas, asi que el promedio es entre cinco.",
    "z_tries_b": "Tres intentos con la contrasena y luego bloqueado.",
    "z_discount_b": "Mas de 50 lleva diez por ciento, asi que 60 debe quedar en 54.",
    "z_convert_b": "De C a F son nueve quintos y luego mas 32. 100 C son 212 F.",
    "z_tie_b": "Votos iguales deben decir que hay empate.",
    "z_fibstep_b": "Debe mostrar 0, 1, 1, 2, 3. Los dos numeros se mueven en mal orden.",
    "z_coins_b": "132 centavos son 1 dólar, 3 decenas y 2 centavos.",
    "z_score_b": "Una respuesta correcta vale uno, una mala no vale nada.",
    "z_sent_b": "Numeros hasta escribir 0, luego el promedio de los anteriores.",
    "z_menu0_b": "El 0 debe pararlo. Ahora vuelve a empezar.",
    "z_else_b": "A los menores de 18 no se les dice nada. Debería decir “out”.",
    "z_swap_b": "Más de 10 es grande y 10 o menos es pequeño. Aquí está al revés.",
    "z_count_b": "Debería contar del 1 al 5.",
    "z_forever_b": "Debería mostrar 3, 2, 1 y luego “go”. Ahora no para nunca.",
    "z_total_b": "Debería sumar 1, 2, 3 y 4 y mostrar 10.",
    "z_two_b": "Debería sumar dos números y mostrar el resultado.",
    "z_return_b": "twice() debería devolver el número doblado para que Display lo muestre.",
    "z_evens_b": "Debería mostrar solo los números pares del 1 al 10.",
    "z_grade_b": "60 aprueba. Ahora mismo 60 suspende.",
    "e_add": "Sumar dos números",
    "e_oddeven": "Par o impar",
    "e_guess": "Adivina el número",
    "e_swap": "Intercambiar dos números",
    "e_factorial": "Un factorial",
    "try_short": "¿Primera vez?",
    "try_go": "Probar un ejemplo",
    "e_area": "Área de un rectángulo",
    "e_sumevens": "Sumar los pares",
    "e_vowel": "Vocal o no",
    "e_leap": "Año bisiesto",
    "e_backwards": "Contar hacia atrás",
    "eg_l4": "Programas del día a día",
    "eg_l5": "Proyectos más grandes",
    "e_bank": "Una cuenta bancaria",
    "e_gradebook": "Un registro de notas",
    "e_paycheck": "Nóminas semanales",
    "e_convert": "Un conversor de unidades",
    "e_splitcheck": "Dividir la cuenta",
    "e_vending": "Una máquina expendedora",
    "e_primelist": "Primos hasta un límite",
    "e_weekday": "¿Qué día de la semana?",
    "e_loan": "Pagar un préstamo",
    "e_rps": "Piedra, papel o tijera",
    # ---- a name for a program nobody named, from what it does (09-names.js)
    "d_rps": "Juega a piedra, papel o tijera",
    "d_weekday": "Calcula el día de la semana de una fecha",
    "d_leap": "Comprueba si un año es bisiesto",
    "d_bank": "Lleva el saldo de una cuenta, con depósitos y retiros",
    "d_loan": "Calcula cuánto tarda en pagarse un préstamo",
    "d_budget": "Análisis de presupuesto",
    "d_rise": "Aumento de {what}",
    "d_fall": "Disminución de {what}",
    "d_doubling": "Duplicación de {what}",
    "d_pop_growth": "Crecimiento de la población",
    "d_compound": "Interés compuesto",
    "d_to": "{from} a {to}",
    "d_total_of": "Total de {what}",
    "d_average_of": "Promedio de {what}",
    "d_pay": "Calcula el sueldo según las horas trabajadas",
    "d_tip": "Calcula la propina y divide la cuenta",
    "d_vending": "Maneja una máquina expendedora y da el cambio",
    "d_change": "Reparte una cantidad de centavos en monedas",
    "d_shop": "Calcula un precio con descuento",
    "d_price": "Calcula lo que cuesta una compra",
    "d_convert": "Convierte entre unidades de medida",
    "d_temps": "Convierte temperaturas de Celsius a Fahrenheit",
    "d_temps_any": "Convierte temperaturas entre Celsius, Fahrenheit y Kelvin",
    "d_primes": "Enumera los números primos hasta un límite",
    "d_prime": "Comprueba si un número es primo",
    "d_fizz": "Juega a FizzBuzz",
    "d_gcd": "Halla el máximo común divisor de dos números",
    "d_fib": "Enumera los números de Fibonacci",
    "d_factorial": "Calcula el factorial de un número",
    "d_reverse": "Escribe al revés las cifras de un número",
    "d_digits": "Cuenta las cifras de un número",
    "d_gradebook": "Califica una clase y resume las notas",
    "d_grades": "Convierte una nota en una letra",
    "d_votes": "Cuenta los votos y nombra al ganador",
    "d_quiz": "Hace preguntas y lleva la puntuación",
    "d_login": "Pide una contraseña",
    "d_guess": "Un juego de adivinar un número",
    "d_vowel": "Comprueba si una letra es vocal",
    "d_stars": "Dibuja un triángulo de estrellas",
    "d_grid": "Muestra una tabla de multiplicar completa",
    "d_table": "Muestra una tabla de multiplicar",
    "d_minmax": "Halla el número menor y el mayor",
    "d_biggest": "Halla el número mayor",
    "d_scores": "Resume un conjunto de notas",
    "d_average": "Calcula un promedio",
    "d_sumevens": "Suma los números pares de {a} a {b}",
    "d_sumevens_any": "Suma los números pares",
    "d_oddeven": "Comprueba si un número es par o impar",
    "d_swap": "Intercambia dos valores",
    "d_area": "Calcula el área de un rectángulo",
    "d_menu": "Ofrece un menú de opciones",
    "d_down_n": "Cuenta hacia atrás desde {n}",
    "d_down": "Cuenta hacia atrás desde un número",
    "d_in_range": "Pregunta hasta que la respuesta está en el rango",
    "d_sum": "Suma los números de {a} a {b}",
    "d_sum_any": "Lleva un total acumulado",
    "d_count": "Cuenta de {a} a {b}",
    "d_add": "Suma dos números",
    "d_greet": "Pide un nombre y saluda",
    "d_checks": "Comprueba si {cond}",
    "d_while": "Repite mientras {cond}",
    "d_until": "Repite hasta que {cond}",
    "d_repeats": "Repite para {v} de {a} a {b}",
    "d_uses": "Llama a {names}",
    "d_asks": "Pide {what}",
    "d_asks_shows": "Pide {what} y muestra el resultado",
    "d_one": "un número",
    "d_two": "dos números",
    "d_three": "tres números",
    "d_numbers": "{n} números",
    "e_fizz": "Fizz y Buzz",
    "e_prime": "¿Es primo?",
    "e_gcd": "Máximo común divisor",
    "e_digits": "Cuántas cifras",
    "e_reverse": "El número al revés",
    "e_grid": "Una cuadrícula de tablas",
    "e_minmax": "El menor y el mayor",
    "e_stars": "Un triángulo de estrellas",
    "e_report": "Un informe de clase",
    "e_login": "Tres intentos de contraseña",
    "e_shop": "Una caja con descuento",
    "e_temps": "Celsius, Fahrenheit y Kelvin",
    "e_votes": "Contar votos",
    "e_fib": "Los números de Fibonacci",
    "e_change": "Dólares, decenas y centavos",
    "e_quiz": "Un test de tres preguntas",
    "e_sentinel": "Números hasta escribir 0",
    "e_picktable": "La tabla que quieras",
    "eg_head": "Ejemplos",
    "eg_more": "Más ejemplos",
    "eg_l1": "Primeros pasos",
    "eg_l2": "Decisiones y bucles",
    "eg_l3": "Números y patrones",
    "e_ask": "Preguntar y mostrar",
    "e_decide": "Una decisión",
    "e_count": "Contar",
    "e_total": "Una suma acumulada",
    "e_while": "Un bucle While",
    "e_grades": "Notas",
    "e_biggest": "El mayor de tres",
    "e_menu": "Un menú",
    "e_keepasking": "Seguir preguntando",
    "e_module": "Un módulo",
    "e_answers": "Una función que devuelve",
    "e_countdown": "Cuenta atrás",
    "try_one": "¿Es tu primera vez? Empieza con uno de estos:",
    "eg_decision": "Una decisión", "eg_loop": "Un bucle", "eg_module": "Un módulo",
    "r_pace": "Cómo se ejecuta", "r_at_once": "De una vez",
    "r_by_step": "Uno a uno", "r_next": "Siguiente paso",
    "r_timed": "Al ritmo del programa",
    "chart_desc": "Diagrama de flujo con {n} formas: {kinds}.",
    "yes_plain": "Sí", "no_plain": "No",
    "more_head": "Opciones del diagrama",
    "o_words": "Idioma y palabras",
    "o_chains": "Encadenar los If largos hacia abajo",
    "o_shapes": "Las formas", "o_paper": "Espaciado y papel",
    "o_for": "Bucles For", "o_for_wide": "Desplegado", "o_for_hex": "Un hexágono",
    "o_everyout": "Un símbolo por cada Mostrar",
    "o_roomy": "Amplio: desplegado, con espacio en cada paso",
    "o_tight": "Compacto: menos figuras, plegado en un bloque",
    "o_columns": "Dividir un diagrama alto en columnas",
    "o_steady": "El mismo dibujo siempre",
    "more": "Opciones", "more_tip": "Más opciones del diagrama",
    "decide": "Decisiones",
    "undo": "Deshacer", "redo": "Rehacer",
    "settings": "Ajustes", "appearance": "Apariencia", "panel_side": "Lado del panel",
    "side_left": "Izquierda", "side_right": "Derecha", "full_screen": "Pantalla completa",
    "full_on": "Llenar la pantalla", "full_off": "Salir de pantalla completa",
    "no_full": "Este navegador no admite pantalla completa.",
    "p_ink": "Tinta", "p_classic": "Clásica", "p_slate": "Pizarra",
    "p_meadow": "Pradera", "p_sunset": "Ocaso", "p_night": "Noche",
    "pseudocode": "Pseudocódigo", "title": "Título",
    "code_big": "Llenar la pantalla", "code_small": "Volver al panel", "done": "Listo",
    "code_lines": "{n} líneas",
    "code_ask": "Introduce {name}: ",
    "code_shares": "lo que comparte el programa",
    "c_head": "Código", "c_write": "Escribir el código",
    "c_one": "En un solo archivo", "c_apart": "Varios archivos",
    "c_files_tip": "Un solo archivo, o uno por diagrama — y un diagrama de un solo flujo se divide en partes si es lo bastante largo",
    "c_one_chart": "Demasiado corto para dividirlo: sale en un solo archivo.",
    "c_cut_into": "Sin módulos: se divide en {n} partes y lo que comparten.",
    "c_files": "{n} archivos", "c_save_all": "Guardarlos todos",
    "c_writing": "Escribiéndolo…",
    "c_zipped": "{n} archivos, en un .zip",
    "your_name": "Tu nombre", "shape": "Forma",
    "language": "Idioma", "key_switch": "Leyenda",
    "tint_switch": "Tintes", "build": "Dibujar el diagrama",
    "drawing": "Dibujando…",
    "no_code": "Todavía no hay pseudocódigo que dibujar.",
    "failed": "No se pudo dibujar.",
    "not_answering": "El estudio no responde ({err}).",
    "empty_chart": "Pega tu pseudocódigo a la izquierda y pulsa Dibujar.",
    "shape_auto": "Automática", "shape_square": "Cuadrada",
    "shape_wide": "Ancha 16:9", "shape_page": "Página", "shape_tall": "Alta",
    "already": "Ya está ahí {path}",
    "copied": "Copiados {n} archivos en {dir}",
    "wrote": "Escrito {path}",
    "open_this": "<- abre este: muestra el diagrama y tiene los enlaces "
                 "de descarga",
    "style_seed": "Semilla de estilo {seed} (usa --seed {seed} para "
                  "volver a dibujarlo igual)",
    "nothing": "No se dio pseudocódigo: no hay nada que dibujar.",
    "studio_at": "El estudio de diagramas está en {url}",
    "leave_open": "Deja esta ventana abierta mientras lo usas; pulsa "
                  "Ctrl+C para detenerlo.",
    "stopped": "Estudio detenido.",
    "site_done": "Esa carpeta es un sitio web. Súbela a GitHub Pages (o "
                 "a cualquier host de archivos) y funcionará igual que "
                 "aquí; los pasos están en {dir}/README.md.",
    "starting": "Iniciando Python en el navegador…",
    "k_head": "Atajos de teclado",
    "k_tip": "Todas las teclas que entiende esta página (?)",
    "k_any": "En cualquier sitio",
    "k_code": "Escribiendo pseudocódigo",
    "k_shape": "Con una forma elegida",
    "k_hand": "Dibujando a mano",
    "k_build": "Dibujar el diagrama (a mano: comprobarlo)",
    "k_undo": "Deshacer y rehacer",
    "k_zoom": "Acercar, alejar, tamaño real",
    "k_close": "Cerrar lo que esté abierto",
    "k_keys": "Mostrar esta lista",
    "k_indent": "Sangrar las líneas, o quitarles la sangría",
    "k_enter": "Una línea nueva, con la sangría que le toca",
    "k_look": "Negrita, cursiva, subrayado",
    "k_size": "Letra más grande o más pequeña",
    "k_next": "La forma siguiente, o la anterior",
    "k_nudge": "Moverla un poco (Mayús: más)",
    "k_drop": "Soltarla",
    "kn_ctrl": "Ctrl",
    "kn_shift": "Mayús",
    "kn_enter": "Intro",
    "kn_del": "Supr",
    "b_about": "Cuánto le falta al dibujo",
    "b_boot": "Iniciando Python en el navegador",
    "b_read": "Leyendo el pseudocódigo",
    "b_lay": "Colocando las formas",
    "b_draw": "Dibujando el diagrama",
    "b_page": "Poniéndolo en la página",
    "ready": "Listo.",
    "boot_failed": "Python no pudo iniciarse en este navegador ({err}).",
    "py_gave_out": "Python se detuvo en este navegador a mitad de este dibujo ({err}).",
}

speaks("es", "Español", ES)
