"""Every word it says, in French."""
from ..words.lookup import speaks

FR = {
    "start": "Début", "end": "Fin", "ret": "Retour",
    "yes": "Vrai", "no": "Faux", "again": "encore ?",
    "key_oval": "Début / Fin", "key_rect": "Traitement",
    "key_io": "Entrée / Sortie", "key_diamond": "Décision",
    "key_hex": "Boucle", "key_sub": "Appeler un module",
    "palette": "Palette", "shapes": "Formes",
    "selected": "Forme sélectionnée", "rest": "Lignes et papier",
    "fill": "Remplissage", "outline": "Contour", "text": "Texte",
    "paper": "Papier", "grid": "Grille", "show_grid": "Afficher la grille",
    "lines": "Lignes et flèches", "reset": "Rétablir toutes les couleurs",
    "download": "Télécharger", "dl_size": "Taille",
    "files": "Fichiers", "import_head": "Importer",
    "dl_svg": "Télécharger le SVG", "dl_png": "Télécharger le PNG",
    "print_it": "Imprimer le schéma",
    "print_head": "Imprimer",
    "print_go": "Imprimer…",
    "print_paper": "Papier",
    "print_wide": "À l’italienne",
    "print_fit": "Tenir sur une page",
    "print_note": "L’impression est sobre : pas de couleurs, seulement des traits et des mots. Quelle imprimante et combien de copies, votre navigateur le demande lui-même — une page n’en a pas le droit.",
    "panel": "Panneau", "panel_tip": "Afficher ou masquer le panneau",
    "png_tip": "Taille du PNG",
    "fit": "Ajuster", "actual": "Réel", "zoom_in": "Agrandir",
    "slide_left": "Gauche", "slide_right": "Droite", "slide_up": "Haut", "slide_down": "Bas",
    "hold_locked": "Fixé", "hold_loose": "Libre",
    "lock_tip": "Garder le schéma en place, en défilant dans la zone",
    "loose_tip": "Déplacez le schéma où vous voulez ; un coin reste toujours visible",
    "zoom_out": "Réduire", "pixels": "pixels",
    "dl_scale": "Fois la taille dessinée",
    "dl_frame": "Ajusté dans une image",
    "png_over": "plus que ce navigateur ne peut dessiner",
    "click_shape": "Cliquez sur une forme de l'organigramme pour ne "
                   "colorer que celle-là.",
    "palette_hint": "Une palette change toutes les formes d'un coup. Ce "
                    "que vous changez ensuite à la main est conservé.",
    "shapes_hint": "Remplissage et contour, pour toutes les formes de ce type.",
    "apply_all": "Appliquer aux {n} formes : {what}", "clear": "Effacer",
    "rendering": "Rendu…",
    "png_big": "Le navigateur n'a pas pu créer un PNG aussi grand. "
               "Essayez une taille plus petite, ou enregistrez le SVG.",
    "png_fail": "Le navigateur n'a pas pu dessiner le PNG. Le "
                "téléchargement du SVG fonctionne toujours.",
    "png_capped": "{want}× dépasse ce qu'un canvas de navigateur "
                  "accepte ; le PNG est donc enregistré à {got}× "
                  "({w} × {h} pixels).",
    "flowchart": "Organigramme",
    "r_head": "Exécuter",
    "r_run": "Lancer",
    "r_stop": "Arrêter",
    "r_code": "En code", "r_lang_pick": "Dans quel langage le code est écrit",
    "r_pseudo": "Pseudocode",
    "r_slowly": "Pas à pas",
    "r_enter": "Entrer",
    "r_hint": "Exécute le programme dont vient l'organigramme : il demande ce qu'il demande à une personne, affiche ce qu'il affiche, et éclaire la forme où il en est. Choisissez un langage pour voir le même programme écrit dedans.",
    "r_started": "Exécution...",
    "r_done": "Terminé.",
    "r_nothing": "Il n'y a encore rien à exécuter.",
    "r_steps": "{n} étapes, {ms} ms.",
    "r_forever": "Cela tourne depuis bien trop longtemps : quelque part il y a une boucle dont il ne sort jamais.",
    "r_zero": "Cela divise par zéro.",
    "r_unknown": "Rien n'a encore été mis dans {name}.",
    "r_odd_op": "Je ne sais pas quoi faire de {op}.",
    "r_half": "Cela ne se lit pas comme un tout : {bit}",
    "r_back": "Retour à l’exécution", "back": "Retour",
    "r_by_hand": "Appuyez sur Vérifier le schéma ; s’il passe, il peut être exécuté ici.",
    "h_runnable": "Cela se lit comme un programme. Vous pouvez l’exécuter.",
    "h_no_start": "Il n’y a aucune forme par laquelle commencer.",
    "h_tangled": "Les boucles de ce schéma se croisent, il ne peut donc pas être écrit comme un programme.",
    "h_not_a_program": "Les mots de ces formes ne se lisent pas comme un programme.",
    "r_build_first": "Construisez un organigramme à partir de "
                     "pseudocode et il pourra être exécuté ici.",
    "r_copy": "Copier",
    "r_copied": "Copié",
    "r_copy_no": "À copier à la main",
    "r_save_code": "Enregistrer",
    "r_pseudo_only": "Choisissez Python, Java, C# ou JavaScript pour voir le code.",
    # ---- où l'exécution a échoué, et ce que la lecture a dû rattraper
    "r_at": "Ligne {line}",
    "r_show_line": "Montre-moi la ligne d'où cela vient",
    "r_in_mod": "dans {name}, appelé depuis la ligne {line}",
    "r_in_mod_only": "dans {name}",
    "r_mean": "Vouliez-vous dire {name} ?",
    "r_unknown_fn": "Il n'existe aucun module ni aucune fonction nommée {name}.",
    "r_odd_here": "Je ne m'attendais pas à {bit} ici.",
    "r_empty_expr": "Il n'y a rien ici pour le calculer.",
    "r_left_over": "Il reste {bit} à la fin, sans rien à quoi le rattacher.",
    "r_open_quote": "Ce texte n'est jamais refermé : il manque un guillemet.",
    "r_open_bracket": "Cette parenthèse est ouverte et jamais refermée.",
    "r_shut_bracket": "Cette parenthèse en referme une qui n'a jamais été ouverte.",
    "r_no_idea": "Je n'arrive pas à lire cette ligne, l'exécution l'a donc enjambée.",
    "r_stepped_over": "Des lignes ont été enjambées : ce qui a été affiché n'est peut-être pas tout.",
    "r_too_deep": "{name} s'est appelé bien trop de fois : quelque part, il ne cesse jamais de s'appeler.",
    "r_args": "{name} demande {want} et en a reçu {got}.",
    "r_no_main": "Il n'y a pas de flux principal ici : l'exécution a donc commencé dans {name}.",
    "w_head": "À regarder",
    "w_found": "{n} à regarder dans le pseudocode :",
    "w_open_if": "Ligne {line} : ce If n'est jamais refermé, donc tout ce qui suit est dedans. Ajoutez un End If là où il doit s'arrêter.",
    "w_open_loop": "Ligne {line} : cette boucle n'est jamais refermée, donc tout ce qui suit tourne avec elle. Ajoutez un End While là où elle doit s'arrêter.",
    "w_open_for": "Ligne {line} : ce For n'est jamais fermé, donc tout ce qui suit tourne avec lui. Ajoutez un End For là où il doit s'arrêter.",
    "w_open_select": "Ligne {line} : ce Select n'est jamais refermé. Ajoutez un End Select là où il doit s'arrêter.",
    "w_no_if": "Ligne {line} : End If, mais aucun If n'est ouvert à refermer.",
    "w_no_loop": "Ligne {line} : ceci referme une boucle, mais aucune boucle n'est ouverte.",
    "w_no_select": "Ligne {line} : End Select, mais aucun Select n'est ouvert à refermer.",
    "w_do_no_test": "Ligne {line} : ce Do ne reçoit aucun test, il tournerait donc sans fin. Terminez-le par Until ... ou Loop While ...",
    "w_until_alone": "Ligne {line} : Until, mais il n'y a ni Do ni Repeat au-dessus à refermer.",
    "w_mend_change": "Remplacer {word} par {instead}",
    "w_mend_drop": "Retirer la ligne {line}",
    "w_mend_insert": "Mettre {text} à la ligne {line}",
    "w_mend_tip": "Double-cliquez pour corriger",
    "n_rect": "Rectangle",
    "an_arrow": "Flèche",
    "word_on_it": "Mot dessus",
    "thickness": "Épaisseur",
    "color_of_it": "Couleur",
    "dashed": "Pointillés",
    "with_head": "Pointe",
    "turn_it_round": "Inverser",
    "m_type": "Écrire dedans",
    "m_copy": "Dupliquer",
    "c_fill": "Couleur de fond", "c_line": "Couleur du bord", "c_words": "Couleur du texte",
    "c_clear": "Aucune couleur propre",
    "m_turn": "Tourner de 90°",
    "m_solid": "Trait plein",
    "m_no_word": "Aucun mot",
    "m_fit": "Ajuster à l'écran",
    "f_save": "Enregistrer dans un fichier",
    "f_open": "Ouvrir un document",
    "f_not_ours": "C’est un fichier JSON, mais pas un schéma enregistré ici.",
    "f_opened": "{name} est ouvert.",
    "f_empty": "Il n’y a rien d’écrit dedans.",
    "n_roundrect": "Boîte arrondie",
    "n_offpage": "Hors page", "n_loop": "Limite de boucle", "n_parallel": "En parallèle",
    "n_text": "Texte", "n_actor": "Personne", "n_callout": "Bulle",
    "n_cube": "Cube", "n_step": "Étape", "n_table": "Tableau",
    "n_stored": "Stocké à l’intérieur", "n_cloud": "Nuage",
    "n_card": "Carte",
    "n_note": "Note",
    "n_docs": "Pages",
    "n_manual": "Saisie manuelle",
    "n_screen": "Écran",
    "n_arrow": "Flèche",
    "n_io_back": "Parallélogramme inversé",
    "n_oval": "Ovale",
    "n_io": "Parallélogramme",
    "n_diamond": "Losange",
    "n_hex": "Hexagone",
    "n_sub": "Boîte à barres",
    "n_trap": "Trapèze",
    "n_doc": "Document",
    "n_store": "Tambour",
    "n_delay": "Attente",
    "n_circle": "Cercle",
    "shapes_for": "Forme de chaque type",
    "shapes_for_hint": "Quelle forme est dessinée pour chaque type d'étape. Ce que l'étape veut dire ne change pas.",
    "size": "Taille",
    "width": "Largeur",
    "height": "Hauteur",
    "turn": "Tourner",
    "fit_words": "Ajuster au texte",
    "colors_here": "Couleurs",
    "odd_shape": "Impossible de dessiner {pair} ; voir --help.",
    "mode_code": "À partir du pseudocode",
    "mode_hand": "À la main",
    "add_shape": "Ajouter une forme",
    "hand_hint": "Déplacez les formes. Cliquez sur l'une, puis sur Relier, puis sur la forme où va la suite.",
    "words_in": "Texte de la forme",
    "connect": "Relier",
    "connect_now": "Cliquez maintenant sur la forme où cela va.",
    "goes_to": "Va vers",
    "nothing_yet": "rien encore",
    "delete": "Supprimer",
    "check": "Vérifier le schéma",
    "checked_good": "Le schéma tient : un seul Début, toutes les formes atteintes, et tous les chemins finissent sur une Fin.",
    "problems": "{n} choses à revoir",
    "pick_shape": "Cliquez sur une forme pour y écrire, la déplacer ou la relier à une autre.",
    "as_chart": "Organigramme",
    "untitled": "Sans titre",
    "p_no_start": "Rien ne commence le flux : chaque forme a quelque chose qui y mène.",
    "p_many_starts": "{n} formes n'ont rien qui y mène. Un organigramme commence à un seul endroit.",
    "p_start_kind": "La forme par laquelle tout commence devrait être un ovale.",
    "p_no_end": "Il n'y a pas de Fin : aucun ovale où le flux s'arrête.",
    "p_unreached": "Rien ne mène à cette forme.",
    "p_dead_end": "Rien ne sort de cette forme, et ce n'est pas une Fin.",
    "p_decision_out": "Une décision a deux sorties, une par réponse. Celle-ci en a {n}.",
    "p_one_out": "Cette forme a {n} sorties. Seule une décision peut en avoir plus d'une.",
    "p_same_labels": "Les deux sorties de cette décision disent la même chose.",
    "p_no_label": "Une sortie de décision a besoin d'un mot.",
    "p_trapped": "Une fois arrivé ici, le flux ne peut plus atteindre de Fin.",
    "p_empty": "Rien n'est écrit dans cette forme.",
    "p_overlap": "Cette forme est posée sur une autre.",
    "p_alone": "Cette forme n'est reliée à rien.",
    "p_line_through": "Une ligne traverse cette forme. Déplacez un peu l'une ou l'autre.",
    "side_chart": "Schéma", "side_colors": "Couleurs", "hide_panel": "Masquer le panneau", "show_panel": "Afficher le panneau",
    "theme": "Clair ou sombre", "theme_auto": "Auto", "theme_light": "Clair", "theme_dark": "Sombre",
    "puzzles": "Défis",
    "pz_one": "Défi {n}",
    "pz_head": "Défis",
    "pz_l1": "Trouve l’erreur",
    "pz_l2": "Fais-le marcher",
    "pz_l3": "Construis-le",
    "pz_check": "Vérifier",
    "pz_right": "Résolu.",
    "pz_wrong": "Pas encore. Avec {give} il a dit {said}.",
    "pz_next": "Énigme suivante", "pz_next_level": "Niveau suivant",
    "pz_job": "Ce qu’il doit faire", "pz_now": "Ce qu’il fait",
    "pz_broke": "Il s’est arrêté avant la fin. On lui a donné {give}.",
    "pz_none": "Il n’y a encore rien à vérifier.",
    "pz_locked": "Résous-en {n} de plus pour ouvrir ceux-ci",
    "pz_done": "{done} sur {all} résolus",
    "pz_nothing": "(rien)",
    "pz_brief": "Le défi",
    "z_greet_b": "Il salue avant d’avoir demandé qui. Demander d’abord, saluer ensuite.",
    "z_range_b": "De 1 à 9 devrait être dans l’intervalle. Pour l’instant tout l’est.",
    "z_double_b": "Il devrait afficher le double du nombre donné.",
    "z_order_b": "Il devrait afficher le total final, 6, et rien en chemin.",
    "z_until_b": "Il devrait compter 1, 2, 3 puis s’arrêter.",
    "z_nested_b": "Deux lignes de deux : 1, 2, 2, 4. La boucle intérieure en manque une.",
    "z_param_b": "show() affiche la lettre x au lieu du nombre qu’on lui a passé.",
    "z_many_b": "Sur les cinq nombres tapés, il devrait dire combien dépassent 10.",
    "z_divide_b": "Il additionne quatre nombres, donc la moyenne se fait sur quatre, pas cinq.",
    "z_sign_b": "Au-dessus de zéro c’est positif, en dessous négatif, et zéro c’est « zero ».",
    "z_twice_b": "Il devrait afficher le mot deux fois.",
    "z_minus_b": "Il devrait retirer le deuxième nombre du premier.",
    "z_early_b": "Il affiche la réponse avant de la calculer. Il devrait afficher le triple.",
    "z_never_b": "Il devrait compter de 5 à 1. Pour l’instant il n’affiche rien.",
    "z_odds_b": "Il devrait additionner les pairs de 1 à 10, soit 30.",
    "z_asked_b": "Il devrait demander trois nombres et additionner ces trois-là.",
    "z_onemore_b": "Il devrait additionner de 1 à 10, soit 55.",
    "z_valid_b": "Il devrait redemander jusqu’à un nombre de 1 à 10, puis l’afficher.",
    "z_smallest_b": "Il devrait afficher le plus grand des quatre nombres tapés.",
    "z_short_b": "add() prend deux nombres. On ne lui en donne qu’un.",
    "z_stops_b": "Il devrait afficher de 5 à 1 puis « go ».",
    "pz_l4": "Fautes plus dures",
    "pz_l5": "Vrais bugs",
    "z_fizz_b": "15 doit dire FizzBuzz. Les tests sont dans le mauvais ordre.",
    "z_prime_b": "Un premier a exactement deux diviseurs. Ici 1 compte comme premier.",
    "z_digits_b": "Il doit dire combien de chiffres a le nombre. 7 en a un.",
    "z_revzero_b": "Il doit retourner les chiffres. 123 devient 321.",
    "z_sumd_b": "Il doit additionner les chiffres du nombre. 123 donne 6.",
    "z_gridrow_b": "Trois lignes : 1 2 3, puis 2 4 6, puis 3 6 9. La ligne ne change jamais.",
    "z_tri_b": "Il doit montrer chaque nombre triangulaire : 1, 3, 6, 10.",
    "z_lowhigh_b": "Il doit montrer le plus petit puis le plus grand des quatre nombres.",
    "z_starsrow_b": "Ligne un une etoile, ligne deux deux etoiles, et ainsi de suite.",
    "z_factloop_b": "Tout fois zero fait zero. 4 factorielle fait 24.",
    "z_report_b": "Cinq notes entrent, donc la moyenne se fait sur cinq.",
    "z_tries_b": "Trois essais pour le mot de passe, puis bloque.",
    "z_discount_b": "Au-dessus de 50, dix pour cent de remise : 60 doit faire 54.",
    "z_convert_b": "C vers F : neuf cinquiemes puis plus 32. 100 C font 212 F.",
    "z_tie_b": "A voix egales il faut dire qu'il y a egalite.",
    "z_fibstep_b": "Il doit montrer 0, 1, 1, 2, 3. Les deux nombres bougent dans le mauvais ordre.",
    "z_coins_b": "132 pence font 1 livre, 3 dizaines et 2 pennies.",
    "z_score_b": "Une bonne reponse vaut un point, une mauvaise rien.",
    "z_sent_b": "Des nombres jusqu'a 0, puis la moyenne de ceux d'avant.",
    "z_menu0_b": "0 doit l'arreter. Pour l'instant il recommence.",
    "z_else_b": "Les moins de 18 ans n’ont droit à rien. Il faudrait dire « out ».",
    "z_swap_b": "Plus de 10 c’est grand, 10 ou moins c’est petit. Ici c’est inversé.",
    "z_count_b": "Il devrait compter de 1 à 5.",
    "z_forever_b": "Il devrait afficher 3, 2, 1 puis « go ». Pour l’instant il ne s’arrête jamais.",
    "z_total_b": "Il devrait additionner 1, 2, 3 et 4 et afficher 10.",
    "z_two_b": "Il devrait additionner deux nombres et afficher le résultat.",
    "z_return_b": "twice() devrait renvoyer le nombre doublé pour que Display l’affiche.",
    "z_evens_b": "Il devrait afficher seulement les nombres pairs de 1 à 10.",
    "z_grade_b": "50 est reçu. Pour l’instant 50 échoue.",
    "e_add": "Additionner deux nombres",
    "e_oddeven": "Pair ou impair",
    "e_guess": "Devine le nombre",
    "e_highest": "Le plus grand jusqu’ici",
    "e_swap": "Échanger deux nombres",
    "e_factorial": "Une factorielle",
    "try_short": "Vous débutez ?",
    "try_go": "Essayer un exemple",
    "e_double": "Fois deux",
    "e_area": "Aire d’un rectangle",
    "e_bigger": "Le plus grand de deux",
    "e_sumevens": "Additionner les pairs",
    "e_onetable": "Une table de multiplication",
    "e_vowel": "Voyelle ou non",
    "e_leap": "Année bissextile",
    "e_power": "Élever à une puissance",
    "e_backwards": "Compter à rebours",
    "eg_l4": "Encore plus dur",
    "eg_l5": "Programmes plus grands",
    "e_fizz": "Fizz et Buzz",
    "e_prime": "Est-ce un nombre premier ?",
    "e_gcd": "Plus grand diviseur commun",
    "e_digits": "Combien de chiffres",
    "e_reverse": "Le nombre à l’envers",
    "e_sumdigits": "Additionner les chiffres",
    "e_grid": "Une grille de tables",
    "e_triangle": "Nombres triangulaires",
    "e_minmax": "Le plus petit et le plus grand",
    "e_stars": "Un triangle d’étoiles",
    "e_report": "Un bulletin de classe",
    "e_login": "Trois essais de mot de passe",
    "e_shop": "Une caisse avec remise",
    "e_temps": "Celsius en Fahrenheit",
    "e_votes": "Compter les voix",
    "e_fib": "Les nombres de Fibonacci",
    "e_change": "Livres, dizaines et pennies",
    "e_quiz": "Un quiz de trois questions",
    "e_sentinel": "Des nombres jusqu’à 0",
    "e_picktable": "La table que tu veux",
    "eg_head": "Exemples",
    "eg_more": "Plus d’exemples",
    "eg_l1": "Premiers pas",
    "eg_l2": "Mettre ensemble",
    "eg_l3": "Aller plus loin",
    "e_ask": "Demander et afficher",
    "e_decide": "Une décision",
    "e_count": "Compter",
    "e_total": "Un total cumulé",
    "e_while": "Une boucle While",
    "e_grades": "Notes",
    "e_biggest": "Le plus grand de trois",
    "e_menu": "Un menu",
    "e_keepasking": "Redemander",
    "e_tables": "Tables de multiplication",
    "e_module": "Un module",
    "e_answers": "Une fonction qui renvoie",
    "e_average": "Une moyenne",
    "e_countdown": "Compte à rebours",
    "e_password": "Un mot de passe",
    "try_one": "Vous débutez ? Commencez par l’un de ceux-ci :",
    "eg_decision": "Une décision", "eg_loop": "Une boucle", "eg_module": "Un module",
    "r_pace": "Comment ça s’exécute", "r_at_once": "D’un coup",
    "r_by_step": "Un par un", "r_next": "Étape suivante",
    "chart_desc": "Organigramme de {n} formes : {kinds}.",
    "yes_plain": "Oui", "no_plain": "Non",
    "more_head": "Options du schéma",
    "o_words": "Langue et mots",
    "o_chains": "Aligner les longues chaînes de If",
    "o_shapes": "Les formes", "o_paper": "Espacement et papier",
    "o_for": "Boucles For", "o_for_wide": "Dépliée", "o_for_hex": "Un hexagone",
    "o_everyout": "Un symbole pour chaque Afficher",
    "o_roomy": "Espacement plus aéré",
    "o_columns": "Répartir un schéma haut en colonnes",
    "o_steady": "Le même dessin à chaque fois",
    "more": "Options", "more_tip": "Plus d’options du schéma",
    "decide": "Décisions",
    "undo": "Annuler", "redo": "Rétablir",
    "settings": "Réglages", "appearance": "Apparence", "panel_side": "Côté du panneau",
    "side_left": "Gauche", "side_right": "Droite", "full_screen": "Plein écran",
    "full_on": "Remplir l’écran", "full_off": "Quitter le plein écran",
    "no_full": "Ce navigateur ne passe pas en plein écran.",
    "p_ink": "Encre", "p_classic": "Classique", "p_slate": "Ardoise",
    "p_meadow": "Prairie", "p_sunset": "Couchant", "p_night": "Nuit",
    "pseudocode": "Pseudocode", "title": "Titre", "your_name": "Votre nom",
    "code_big": "Remplir l’écran", "code_small": "Revenir au panneau", "done": "Terminé",
    "code_esc": "Échap pour fermer", "code_lines": "{n} lignes",
    "shape": "Forme",
    "language": "Langue", "key_switch": "Légende", "tint_switch": "Teintes",
    "build": "Dessiner l'organigramme", "drawing": "Dessin…",
    "no_code": "Il n'y a pas encore de pseudocode à dessiner.",
    "failed": "Le dessin a échoué.",
    "not_answering": "Le studio ne répond pas ({err}).",
    "empty_chart": "Collez votre pseudocode à gauche, puis cliquez sur "
                   "Dessiner.",
    "shape_auto": "Auto", "shape_square": "Carré", "shape_wide": "Large 16:9",
    "shape_page": "Page", "shape_tall": "Haut",
    "already": "Déjà là {path}",
    "copied": "{n} fichiers copiés dans {dir}",
    "wrote": "Écrit {path}",
    "open_this": "<- ouvrez celui-ci : il montre l'organigramme et porte "
                 "les liens de téléchargement",
    "style_seed": "Graine de style {seed} (passez --seed {seed} pour le "
                  "redessiner à l'identique)",
    "nothing": "Aucun pseudocode donné -- rien à dessiner.",
    "studio_at": "Le studio d'organigrammes tourne sur {url}",
    "leave_open": "Laissez cette fenêtre ouverte pendant que vous vous en "
                  "servez ; Ctrl+C pour l'arrêter.",
    "stopped": "Studio arrêté.",
    "site_done": "Ce dossier est un site web. Mettez-le sur GitHub Pages "
                 "(ou tout hébergeur de fichiers) et il marchera comme "
                 "ici ; les étapes sont dans {dir}/README.md.",
    "starting": "Démarrage de Python dans le navigateur…",
    "ready": "Prêt.",
    "boot_failed": "Python n'a pas pu démarrer dans ce navigateur ({err}).",
}

speaks("fr", "Français", FR)
